apiVersion: v1
kind: Secret
metadata:
  name: {{ include "air-bench.benchmark.fullname" . }}-secrets
  labels:
    {{- include "air-bench.labels" . | nindent 4 }}
type: Opaque
stringData:
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
