apiVersion: v1
kind: Service
metadata:
  name: {{ include "air-bench.vllm.fullname" . }}
  labels:
    {{- include "air-bench.labels" . | nindent 4 }}
    app.kubernetes.io/component: vllm
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.vllm.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: vllm
    app.kubernetes.io/instance: {{ .Release.Name }}
